### ISSUE TITLE
where is aql and other tools source code ?i can not find them ?

### ISSUE THREAD

**Issue by shuzhifeng** [aerospike/aerospike-tools.docker#1]
I want to install the aql tool on reddhat5U7,but i can not find the source code to rebuild them .

**Comment by volmarl** [comment]
Sorry we currently don't have the source codes on github. For redhat 7 you should eb able to use our current RPM and ensure that python dependencies are met.

Please see download RPM at:

http://www.aerospike.com/download/tools/3.5.11/artifact/el6

You could also use docker and build this container.

**Comment by anshprat** [comment]
@volmarl ping - good to close this ?  :)
