### ISSUE TITLE
Error when pulling Aerospike tools image 

### ISSUE THREAD

**Issue by AbdulghaffarExalt** [aerospike/aerospike-tools.docker#27]
docker pull aerospike/aerospike-tools
Using default tag: latest
Error response from daemon: manifest for aerospike/aerospike-tools:latest not found: manifest unknown: manifest unknown

**Comment by kumar-aaditya-575** [comment]
facing the same issue. can't pull the image.

**Comment by kportertx** [comment]
Looks like the `latest` tag was removed - unsure if this was by mistake or not (:question:  @mcoberly2). You will need to specify which version that you want.

https://hub.docker.com/r/aerospike/aerospike-tools/tags

**Comment by mcoberly2** [comment]
@AbdulghaffarExalt @kumar-aaditya-575 
Thanks for raising this issue of the latest tag missing. 
The issue has been resolved.  
Latest has been restored.
