### ISSUE TITLE
Segmentation fault during ascli put call

### ISSUE THREAD

**Issue by etki** [aerospike/aerospike-tools.docker#3]
Hi, i've just pulled `aerospike` and `aerospike/aerospike-tools` packages and the following call ended in a segmentation fault:

```
root@backend:/var/www/supporting/aerospike# docker run --rm aerospike/aerospike-tools ascli -h 172.17.0.1 put cache smoke acknowledgement '{"success": true}'
/aerospike/wrapper: line 36:     8 Segmentation fault      $CMD "$@"
```

However, the following call has made it through with no error:

```
root@backend:/var/www/supporting/aerospike# docker run --rm aerospike/aerospike-tools ascli -h 172.17.0.1 put cache smoke acknowledgement '{"success": "true"}'
```

Mentioned namespace resides only in memory, set, key and bin should not have existed before this call. I suspect there is some error in JSON serialization library.

**Comment by volmarl** [comment]
ascli has been deprecated. 
Closing
