### ISSUE TITLE
Missing python libs

### ISSUE THREAD

**Issue by helder-moreira** [aerospike/aerospike-tools.docker#9]
Latest version (3.15.3.2) is not working due to some missing python libs, namely __pyOpenSSL__ __pyasn1__ __toml__ and __jsonschema__.

Simply pulling and running container does not work:

```bash
$ docker pull aerospike/aerospike-tools
$ docker run -it --rm aerospike/aerospike-tools asadm
ERROR: Config file parse error: /etc/aerospike/astools.conf No module named toml
```

Best regards,

Helder M.

**Comment by bbulkow** [comment]
Helder, to allow us to track this down, what is the operating system and exact distribution that you are using?

PyOpenSSL can be a little finicky so we are looking at the different distributions and how to adapt.

Thanks

**Comment by helder-moreira** [comment]
I am on Arch Linux, but I have also tried on both Ubuntu Trusty and Xenial. Additionally, I have also tried in a Kubernetes cluster, which is where the problem occurred to me first.

Installing the missing libs using __pip__ solves the problem for me. I have done so by changing the Dockerfile to install __python-pip__ and running __pip install pyOpenSSL pyasn1 toml jsonschema__.

**Comment by volmarl** [comment]
Tools were refactored to use PEX

example:

https://github.com/aerospike/aerospike-admin#installing-aerospike-admin
